FROM node:20-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install --production=false

COPY frontend .
ENV NEXT_PUBLIC_API_BASE=http://localhost:8000

RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start", "--", "-H", "0.0.0.0", "-p", "3000"]
